# DAY17

## 异常处理

Python 使用 try 和 except 来优雅地处理错误。优雅地退出（或优雅地处理）错误是一个简单的编程习语--程序检测到严重错误条件，并因此以可控的方式 "优雅地退出"。作为优雅退出的一部分，程序通常会在终端或日志中打印描述性错误信息，这使我们的应用程序更加健壮。异常的起因往往是程序本身的外部因素。例如，输入错误、文件名错误、找不到文件、IO 设备故障等。优雅地处理错误可以防止应用程序崩溃。

我们在上一节中介绍了不同的 Python 错误类型。如果我们在程序中使用 try 和 except，那么在这些代码块中就不会产生错误。

```python
try:
    code in this block if things go well
except:
    code in this block run if things go wrong
```

```python
try:
    name = input('Enter your name:')
    year_born = input('Year you were born:')
    age = 2019 - year_born
    print(f'You are {name}. And your age is {age}.')
except:
    print('Something went wrong')
```


在上面的示例中，异常代码块将会运行，但我们并不清楚问题所在。为了分析问题，我们可以使用不同的错误类型和 except。

在下面的示例中，它将处理错误，并告诉我们引发的错误类型。

```python
try:
    name = input('Enter your name:')
    year_born = input('Year you born:')
    age = 2019 - int(year_born)
    print('You are {name}. And your age is {age}.')
except Exception as e:
    print(e)
```

## 在 Python 中打包和解包参数

我们使用两个运算符：

* `* 用于元组`
* `** 用于字典`

解包

```python
def sum_of_five_nums(a, b, c, d, e):
    return a + b + c + d + e

lst = [1, 2, 3, 4, 5]
# 对list进行解包
print(sum_of_five_nums(*lst))  # 15
```

我们还可以在 range 内置函数中使用解包，该函数需要一个起点和终点。

```python
numbers = range(2, 7)  # normal call with separate arguments
print(list(numbers)) # [2, 3, 4, 5, 6]
args = [2, 7]
numbers = range(*args)  # call with arguments unpacked from a list
print(numbers)      # [2, 3, 4, 5,6]
```

这也是解包的一个例子

```python
countries = ['Finland', 'Sweden', 'Norway', 'Denmark', 'Iceland']
fin, sw, nor, *rest = countries
print(fin, sw, nor, rest)   # Finland Sweden Norway ['Denmark', 'Iceland']
numbers = [1, 2, 3, 4, 5, 6, 7]
one, *middle, last = numbers
print(one, middle, last)      #  1 [2, 3, 4, 5, 6] 7
```

解包字典

```python
def unpacking_person_info(name, country, city, age):
    return f'{name} lives in {country}, {city}. He is {age} year old.'
dct = {'name':'Asabeneh', 'country':'Finland', 'city':'Helsinki', 'age':250}
print(unpacking_person_info(**dct)) # Asabeneh lives in Finland, Helsinki. He is 250 years old.
```

接收可变数量的位置参数

```python
def sum_all(*args):
    s = 0
    for i in args:
        s += i
    return s
print(sum_all(1, 2, 3))             # 6
print(sum_all(1, 2, 3, 4, 5, 6, 7)) # 28
```

```python
def packing_person_info(**kwargs):
    for key in kwargs:
        print(f"{key} = {kwargs[key]}")
    return kwargs

print(packing_person_info(name="Asabeneh",
      country="Finland", city="Helsinki", age=250))
```

扩展运算符

```python
lst_one = [1, 2, 3]
lst_two = [4, 5, 6, 7]
lst = [0, *lst_one, *lst_two]
print(lst)          # [0, 1, 2, 3, 4, 5, 6, 7]
country_lst_one = ['Finland', 'Sweden', 'Norway']
country_lst_two = ['Denmark', 'Iceland']
nordic_countries = [*country_lst_one, *country_lst_two]
print(nordic_countries)  # ['Finland', 'Sweden', 'Norway', 'Denmark', 'Iceland']
```

Enumerate

如果我们对列表的索引感兴趣，可以使用内置函数 enumerate 来获取列表中每个项的索引。

```py
for index, item in enumerate([20, 30, 40]):
    print(index, item)
```

有时，我们希望在循环浏览列表时合并列表。请看下面的示例：

```py
fruits = ['banana', 'orange', 'mango', 'lemon', 'lime']        
vegetables = ['Tomato', 'Potato', 'Cabbage','Onion', 'Carrot']
fruits_and_veges = []
for f, v in zip(fruits, vegetables):
    fruits_and_veges.append({'fruit':f, 'veg':v})

print(fruits_and_veges)
# [{'fruit': 'banana', 'veg': 'Tomato'}, {'fruit': 'orange', 'veg': 'Potato'}, {'fruit': 'mango', 'veg': 'Cabbage'}, {'fruit': 'lemon', 'veg': 'Onion'}, {'fruit': 'lime', 'veg': 'Carrot'}]
```
